modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/fallOut015/tutorial/issues" #optional
[[mods]] #mandatory
modId="tutorial" #mandatory
version="${file.jarVersion}" #mandatory
displayName="fallOut015's Tutorial Mod" #mandatory
updateJSONURL="https://raw.githubusercontent.com/fallOut015/tutorial/main/src/main/resources/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/tutorial-mod-fallout015" #optional
logoFile="tutorial.png" #optional
credits="Thanks for this tutorial mod goes to fallOut015" #optional
authors="fallOut015" #optional
description='''
A Tutorial Mod by fallOut015.
'''
[[dependencies.tutorial]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
